### ISSUE TITLE
suggest removing as this is a duplicate of the repo with the same name in the GACS organization repo collection

### ISSUE THREAD

**Issue by brandonnodnarb** [agrisemantics/2018_02_berlin#1]

**Comment by brandonnodnarb** [comment]
Actually, I just realised the repo in the GASC Org is fork.  I now suggest deleting the forked repo and changing ownership of this one (making the owner the GACS Org).

**Comment by tombaker** [comment]
@brandonnodnarb There is no longer any need for this to be a separate repo.  (The more repos there are, the more need to be tracked!)  The  content of this repo could perhaps be moved to the [archival repo](https://github.com/agrisemantics/archive).

**Comment by brandonnodnarb** [comment]
As I understand it then, simply moving the content to the archive and then removing the repo should do the trick?

We should also make sure the archive is linked from the GACS org.

**Comment by tombaker** [comment]
> As I understand it then, simply moving the content to the archive and then removing the repo should do the trick?

Yes.

**Comment by brandonnodnarb** [comment]
moved to archive
